// <auto-generated />
namespace RealEstate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class realestate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(realestate));
        
        string IMigrationMetadata.Id
        {
            get { return "202010210514364_realestate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
