// <auto-generated />
namespace RealEstate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class realestateV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(realestateV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202010230920598_realestateV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
